language: node_js

node_js:
  - "9.3.0"

script:
  - echo "Deploy"

install:
  - npm install -g firebase-tools


after_success:
  -  firebase use master
  - firebase deploy --token "1/bIrEVG9r435PtbnnCDK4Tc8J9Rg-DZj5YGKcOtAEW2M"